//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab2HW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type_Shop
    {
        public int IdType_Shop { get; set; }
        public int IdShop { get; set; }
        public int IdType { get; set; }
    
        public virtual Shop Shop { get; set; }
        public virtual Type Type { get; set; }
    }
}
